### ISSUE TITLE
Navigation bar hides a part view

### ISSUE THREAD

**Issue by Nimtego** [Nimtego/iTunes#112]
It is revealed in the emulator

**Comment by Reeson2003** [comment]
**Describe the bug**
Экранные клавиши на эмуляторе перекрывают кнопки навигации

**To Reproduce**
Steps to reproduce the behavior:
1. Запустить в эмуляторе
2. Нажать books

**Expected behavior**
Переход на вкладку books

**Actual behavior**
Приложение сворачивается

**Screenshots**
<img width="453" alt="Снимок экрана 2019-07-25 в 10 39 24" src="https://user-images.githubusercontent.com/21168645/61855658-27266d00-aec9-11e9-81c3-90eede5d3d7d.png">
